### ISSUE TITLE
darling-dkms: fortify-string.h:358:63: error: expected identifier or ‘(’ before ‘{’ token

### ISSUE THREAD

**Issue by bquast** [darlinghq/darling#1179]
**Build Log**
What is the build error?
```
./include/linux/fortify-string.h:358:63: error: expected identifier or ‘(’ before ‘{’ token
  358 |                              p_size_field, q_size_field, op) ({         \
      |                                                               ^
./include/linux/fortify-string.h:369:26: note: in expansion of macro ‘__fortify_memcpy_chk’
  369 | #define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                  \
      |                          ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/darling-mach/r3717.26e55e111/build/osfmk/libsa/string.h:63:18: note: in expansion of macro ‘memcpy’
   63 | extern void     *memcpy(void *, const void *, size_t);
      |                  ^~~~~~
./include/linux/fortify-string.h:358:63: error: expected identifier or ‘(’ before ‘{’ token
  358 |                              p_size_field, q_size_field, op) ({         \
      |                                                               ^
./include/linux/fortify-string.h:373:27: note: in expansion of macro ‘__fortify_memcpy_chk’
  373 | #define memmove(p, q, s)  __fortify_memcpy_chk(p, q, s,                 \
      |                           ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/darling-mach/r3717.26e55e111/build/osfmk/libsa/string.h:65:18: note: in expansion of macro ‘memmove’
   65 | extern void     *memmove(void *, const void *, size_t);
      |                  ^~~~~~~
./include/linux/fortify-string.h:115:9: error: expected identifier or ‘(’ before ‘__builtin_choose_expr’
  115 |         __builtin_choose_expr(__is_constexpr(__builtin_strlen(p)),      \
      |         ^~~~~~~~~~~~~~~~~~~~~                                                           ^
```
[Build log (gist)](https://gist.github.com/bquast/97056dd9c6a5c530812a97e091b92c15) (also attached as darling-dkms.log, further attached terminal output as darling.txt) 

**System Information**
What system are you building with?

| Software | Version |
| - | - |
| Clang | 13.0.1 |
| CMake | 3.23.2 |
| Linux Kernel | 5.18.3-arch1-1 |
| Darling | 26e55e11175da4846511764e650062fb29f3e3f7 |

[darling-dkms.log](https://github.com/darlinghq/darling/files/8917628/darling-dkms.log)
[darling.txt](https://github.com/darlinghq/darling/files/8917629/darling.txt)

**Comment by bquast** [comment]
sorry not sure why the table isn't rendering properly

**Comment by bquast** [comment]
Okay, I managed to get it working on the LTS kernel (5.15.47-1). Specifically I:

1. `sudo pacman -S linux-lts`
2. `reboot`
3. `sudo pacman -S linux-lts-headers`

**Comment by chinese-wzq** [comment]
I think this is a kernel source bug.Can you report it?

**Comment by bquast** [comment]
It seems to be, I'm on Arch, on more recent version of 5.18 it works again, no problem.

How should I report it?
