### ISSUE TITLE
Strange lib load order problem

### ISSUE THREAD

**Issue by neon12345** [darlinghq/darling#102]
I'm trying to use clang with darling on a small hello world program.
The result is that it sometimes works and sometimes not in an unpredictable way.

When clang invokes the linker it uses:
"dyld ld -demangle -dynamic -arch x86_64 -macosx_version_min 10.8.0 -o a.out test.o -lSystem"

This does work sometimes but not always! Using the line on its own always fails.

What always works on its own is:
"dyld ld -demangle -dynamic -arch x86_64 -macosx_version_min 10.8.0 -lSystem -o a.out test.o "

So why does this work sometimes when used by clang? Is this the right command used by clang or should it be the second one? Looking at a native clang run it seems that -o xxx is always in front of the -lxxx library loads.

This is what happens when it does not work:

Undefined symbols for architecture x86_64:
  "___stderrp", referenced from:
      _main in test.o
  "_fprintf", referenced from:
      _main in test.o
ld: symbol(s) not found

**Comment by neon12345** [comment]
Ok, the ld only cmd has the same behavior without clang.
When it does not work there is a call  to "__darwin_dlsym" with "fprintf". There is no call with a symbol containing "fprintf" when it works.

**Comment by LubosD** [comment]
The problem is the code in master branch is rather unstable. it works once, then it doesn't another time... This is one of the reasons for http://www.darlinghq.org/news/rethinking-the-libsystem-approach

If you tell me where you got your clang from (or upload it somewhere), I'll make sure it works in this branch of Darling.

**Comment by neon12345** [comment]
I have used:
BaseSystem.dmg (from the ElCapitan upgrade installer inside the top level dmg) for ditto
and
http://adcdownload.apple.com/Developer_Tools/Xcode_7.1.1/Xcode_7.1.1.dmg

Extract the files and use ditto to remove the hfsComression. 

Clang is in Xcode.

**Comment by neon12345** [comment]
Are there any build instructions for the libsystem branch? Where can I find a libdispatch with the needed headers. I'm using debian jessie.

**Comment by LubosD** [comment]
It contains submodules, so you need to run git submodule init && git submodule update. You also need to build the kernel module in src/lkm, load it and give your user write access to /dev/mach.

But I'll also try it myself.

BTW: you can use the darling-dmg FUSE module to mount .dmg files.

**Comment by LubosD** [comment]
I'm now trying an older llvm-gcc binary and it's crashing with darling-libsystem due to a problem with NXGetLocalArchInfo returning NULL. I'll fix it soon.
It's very likely clang calls the same function.

**Comment by neon12345** [comment]
Hm, got some memory error and an unimplemented syscall:
... �x�5�/test-443bb0.o -x c++ test.cpp
Unimplemented syscall (244)
clang: error: unable to execute command: posix_spawn failed: Function not implemented

**Comment by LubosD** [comment]
With the very latest darling-libsystem code (I made some important changes around libstdc++ and libc++), I don't see any garbage, but posix_spawn is truly not implemented in this branch yet. I'll try to correct that soon.

Can you also show me the exact command you're running? Just to be sure. I tried this:
````
dyld ./Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang /tmp/hello.c -o /tmp/hello -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin4.2.0-gentoo
Thread model: posix
 "/home/lubos/.darling/mounts/mount2/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.0.0-gentoo -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name hello.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 253.6 -v -dwarf-column-info -resource-dir /home/lubos/.darling/mounts/mount2/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0 -fdebug-compilation-dir /home/lubos/.darling/mounts/mount2 -ferror-limit 19 -fmessage-length 429 -mstackrealign -fblocks -fblocks-runtime-optional -fobjc-runtime=macosx-10.0.0 -fobjc-dispatch-method=non-legacy -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o   /hello-77445b.o -x c /tmp/hello.c
Unimplemented syscall (244)
clang: error: unable to execute command: posix_spawn failed: Function not implemented
````

**Comment by neon12345** [comment]
leave the -o or try with hello.cpp

**Comment by neon12345** [comment]
Can you give me a hint on where to start adding syscalls and what is needed? Some code exists in multiple locations so I'm not sure what is really needed here at first glance.

**Comment by LubosD** [comment]
If you want to add a system call, first find it here: http://www.opensource.apple.com/source/xnu/xnu-1504.3.12/bsd/kern/syscalls.master There you can see its number and signature.

Then implement it in one of the subfolders here: https://github.com/darlinghq/darling/tree/darling-libsystem/src/kernel/emulation/linux
Add it to CMakeLists.txt and syscalls.c.

**Comment by LubosD** [comment]
I've implemented posix_spawn(). It is not complete (some signal masking is still missing + the possibility to choose a FAT binary architecture when executing), but sufficient for clang.
There are still issues though, which I will fix during the next days:

* _dirhelper() is unimplemented (in src/duct), which causes the garbage you mentioned above.
* __pthread_kill (syscall 328) is missing.

**Comment by LubosD** [comment]
_dirhelper() is done and working. Apple's ld seems to query sysctl({CTL_KERN, KERN_OSRELEASE}) though and doesn't like "4.2.0-gentoo" that it gets on my system, so I need to finish #103.

BTW, do you happen to know how to pass OS X SDK location to clang?

**Comment by LubosD** [comment]
Compilation now seems to fully work (updated kernel module needed!):

````
$ SDKROOT=/home/lubos/Projects/MacOSX10.8.sdk/ ~/Projects/darling-root/bin/dyld64 /tmp/mount/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ~/helloworld.c -o /tmp/test
$ file /tmp/test
/tmp/test: Mach-O 64-bit x86_64 executable
````
