### ISSUE TITLE
make lkm  error: dereferencing pointer to incomplete type 'struct task_struct

### ISSUE THREAD

**Issue by cena-luo** [darlinghq/darling#409]
I make lkm get error:

> Darling also requires a kernel module named darling-mach:
> 
> make lkm
> sudo make lkm_install

this is progress:

ubuntu@10-8-28-125:~/darling/build$ git submodule update
Submodule path '../src/lkm': checked out '5fc5c9886fd8ca68d1ba78c4b20aff007b09864d'
ubuntu@10-8-28-125:~/darling/build$ make lkm
Built target migcom
Built target migexe
Built target lkm_generate
Building the Linux kernel module
make[4]: Entering directory '/home/ubuntu/darling/src/lkm'
make -C /lib/modules/4.4.0-131-generic/build M=/home/ubuntu/darling/src/lkm modules
make[5]: Entering directory '/usr/src/linux-headers-4.4.0-131-generic'
  CC [M]  /home/ubuntu/darling/src/lkm/darling/module.o
In file included from include/linux/srcu.h:33:0,
                 from include/linux/notifier.h:15,
                 from include/linux/memory_hotplug.h:6,
                 from include/linux/mmzone.h:738,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /home/ubuntu/darling/src/lkm/darling/module.c:1:
/home/ubuntu/darling/src/lkm/darling/module.c: In function 'in_darling_group':
include/linux/cred.h:284:35: error: dereferencing pointer to incomplete type 'struct task_struct'
  rcu_dereference_protected(current->cred, 1)
                                   ^
include/linux/rcupdate.h:618:12: note: in definition of macro '__rcu_dereference_protected'
  ((typeof(*p) __force __kernel *)(p)); \
            ^
include/linux/cred.h:284:2: note: in expansion of macro 'rcu_dereference_protected'
  rcu_dereference_protected(current->cred, 1)
  ^
/home/ubuntu/darling/src/lkm/darling/module.c:9:28: note: in expansion of macro 'current_cred'
  const struct cred* cred = current_cred();
                            ^
/home/ubuntu/darling/src/lkm/darling/module.c:17:30: error: 'struct group_info' has no member named 'gid'
   if (gid_eq(cred->group_info->gid[i], grp))
                              ^
scripts/Makefile.build:277: recipe for target '/home/ubuntu/darling/src/lkm/darling/module.o' failed
make[6]: *** [/home/ubuntu/darling/src/lkm/darling/module.o] Error 1
Makefile:1437: recipe for target '_module_/home/ubuntu/darling/src/lkm' failed
make[5]: *** [_module_/home/ubuntu/darling/src/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.4.0-131-generic'
Makefile:290: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/home/ubuntu/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:57: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:53386: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:53393: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:14813: recipe for target 'lkm' failed
make: *** [lkm] Error 2
ubuntu@10-8-28-125:~/darling/build$ 

I was build in ubuntu 16.04,and I was make in build folder.
please help me ,thanks~~

**Comment by cena-luo** [comment]
@LubosD   new error coming... please...


/home/ubuntu/darling/src/lkm/darling/traps.c: In function 'mach_init':
/home/ubuntu/darling/src/lkm/darling/traps.c:193:1: warning: label 'fail' defined but not used [-Wunused-label]
 fail:
 ^
  CC [M]  /home/ubuntu/darling/src/lkm/darling/module.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/host_info.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/evprocfd.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/evpsetfd.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/pthread_kill.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/psynch_support.o
  CC [M]  /home/ubuntu/darling/src/lkm/darling/foreign_mm.o
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c: In function 'foreignmm_init':
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:27:11: error: implicit declaration of function 'kthread_create_worker' [-Werror=implicit-function-declaration]
  worker = kthread_create_worker(0, "darling-foreign_mm");
           ^
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:27:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  worker = kthread_create_worker(0, "darling-foreign_mm");
         ^
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c: In function 'foreignmm_exit':
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:32:2: error: implicit declaration of function 'kthread_destroy_worker' [-Werror=implicit-function-declaration]
  kthread_destroy_worker(worker);
  ^
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c: In function 'foreignmm_execute':
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:64:2: error: implicit declaration of function 'kthread_init_work' [-Werror=implicit-function-declaration]
  kthread_init_work(&work.kw, foreignmm_run);
  ^
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:65:2: error: implicit declaration of function 'kthread_queue_work' [-Werror=implicit-function-declaration]
  kthread_queue_work(worker, &work.kw);
  ^
/home/ubuntu/darling/src/lkm/darling/foreign_mm.c:66:2: error: implicit declaration of function 'kthread_flush_work' [-Werror=implicit-function-declaration]
  kthread_flush_work(&work.kw);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:277: recipe for target '/home/ubuntu/darling/src/lkm/darling/foreign_mm.o' failed
make[6]: *** [/home/ubuntu/darling/src/lkm/darling/foreign_mm.o] Error 1
Makefile:1437: recipe for target '_module_/home/ubuntu/darling/src/lkm' failed
make[5]: *** [_module_/home/ubuntu/darling/src/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.4.0-131-generic'
Makefile:290: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/home/ubuntu/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:57: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:52968: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:52975: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:14813: recipe for target 'lkm' failed
make: *** [lkm] Error 2

**Comment by LubosD** [comment]
I'm afraid I have to stop as this point and say that Linux 4.9 (released over a year and a half ago) is a minimum reuirement, because reimplementing this functionality for older kernels would be too much work.

**Comment by cena-luo** [comment]
@LubosD  Thank you very much, I update my linux kneel to 4.16.0,and build success... 

first I build I don't kown this requirement...now success... thank you...


> Darling [/home/ubuntu/darling/build]$ uname -a
> Darwin 10-8-28-125 16.0.0 Darwin Kernel Version 16.0.0 x86_64
