### ISSUE TITLE
lkm doesn't build on kernel 4.8

### ISSUE THREAD

**Issue by npyl** [darlinghq/darling#309]
Hello, I tried to build lkm on ubuntu kernel 4.8.0-52-generic and it fails.

`[ 50%] Built target migcom
[ 50%] Building the Linux kernel module
make[4]: Entering directory '/media/npyl/darling/src/lkm'
make -C /lib/modules/4.8.0-52-generic/build M=/media/npyl/darling/src/lkm modules
make[5]: Entering directory '/usr/src/linux-headers-4.8.0-52-generic'
  CC [M]  /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:43:0:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h: In function ‘__access_remote_vm_darling’:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h:27:44: warning: passing argument 6 of ‘get_user_pages_remote’ makes integer from pointer without a cast [-Wint-conversion]
                                 gup_flags, &page, &vma);
                                            ^
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct.h:54:0,
                 from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:36:
./include/linux/mm.h:1311:6: note: expected ‘int’ but argument is of type ‘struct page **’
 long get_user_pages_remote(struct task_struct *tsk, struct mm_struct *mm,
      ^
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:43:0:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h:27:51: error: passing argument 7 of ‘get_user_pages_remote’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                                 gup_flags, &page, &vma);
                                                   ^
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct.h:54:0,
                 from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:36:
./include/linux/mm.h:1311:6: note: expected ‘struct page **’ but argument is of type ‘struct vm_area_struct **’
 long get_user_pages_remote(struct task_struct *tsk, struct mm_struct *mm,
      ^
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:43:0:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h:26:23: error: too few arguments to function ‘get_user_pages_remote’
                 ret = get_user_pages_remote(tsk, mm, addr, 1,
                       ^
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct.h:54:0,
                 from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:36:
./include/linux/mm.h:1311:6: note: declared here
 long get_user_pages_remote(struct task_struct *tsk, struct mm_struct *mm,
      ^
cc1: some warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o' failed
make[6]: *** [/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o] Error 1
Makefile:1491: recipe for target '_module_/media/npyl/darling/src/lkm' failed
make[5]: *** [_module_/media/npyl/darling/src/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.8.0-52-generic'
Makefile:279: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/media/npyl/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:85: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:35322: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:35329: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:10081: recipe for target 'lkm' failed
make: *** [lkm] Error 2
`

Thank you

Edit: Its the same function as in issue #306 but its a different error so I thought I should open a new issue...

**Comment by bugaevc** [comment]
> Entering directory '/media/npyl/FUCKKKKKK/darling/src/lkm'

I like it how you name your drives 😂

**Comment by LubosD** [comment]
Please `git pull` and `git submodules update` and try the build again.

**Comment by npyl** [comment]
Thank you !!!! It worked but produced another error. ( I will show you the log )
Then I changed a #if to #elif and it compiled lkm successfully!!! So thank you very much...
 Please check out the error because I think that the source may need one more tweak!!! :)

`make[5]: Entering directory '/usr/src/linux-headers-4.8.0-52-generic'
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/ipc_kmsg.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/ipc_labelh.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/ipc_notify.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/mach_port.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/mach_debug.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/ipc/mach_kernelrpc.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/kern/sync_sema.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/duct/duct_kern_thread_call.o
  CC [M]  /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:43:0:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h: In function ‘__access_remote_vm_darling’:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h:22:0: error: unterminated #if
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(4,10,0)
 ^
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c: In function ‘duct_vm_map_copyin_common’:
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:252:13: error: implicit declaration of function ‘__access_process_vm’ [-Werror=implicit-function-declaration]
        rd = __access_process_vm(ltask, src_addr, copy->cpy_kdata, len, 0);
             ^
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c: In function ‘__access_remote_vm_darling’:
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:389:1: error: expected declaration or statement at end of input
 }
 ^
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:389:1: error: expected declaration or statement at end of input
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:389:1: warning: no return statement in function returning non-void [-Wreturn-type]
In file included from /media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c:43:0:
/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.c: At top level:
/media/npyl/darling/src/lkm/osfmk/duct/access_process_vm.h:8:12: warning: ‘__access_remote_vm_darling’ defined but not used [-Wunused-function]
 static int __access_remote_vm_darling(struct task_struct *tsk, struct mm_struct
            ^
cc1: some warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o' failed
make[6]: *** [/media/npyl/darling/src/lkm/osfmk/duct/duct_vm_map.o] Error 1
Makefile:1491: recipe for target '_module_/media/npyl/darling/src/lkm' failed
make[5]: *** [_module_/media/npyl/darling/src/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.8.0-52-generic'
Makefile:279: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/media/npyl/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:85: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:35322: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:35329: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:10081: recipe for target 'lkm' failed
make: *** [lkm] Error 2
`

Thank you very much!!! :D

**Comment by LubosD** [comment]
My bad, please try it again.

**Comment by npyl** [comment]
Worked perfectly!!!! :) Thank you!!!
