### ISSUE TITLE
 _CGPointCreateDictionaryRepresentation in CGGeometry.o ld: symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by cena-luo** [darlinghq/darling#410]
when I was make in build folder,get this error....
I build in ubuntu 16.04...

[ 90%] Linking C shared library CoreGraphics
Undefined symbols for architecture i386:
  "_CRelease", referenced from:
      _CGPointCreateDictionaryRepresentation in CGGeometry.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics.dir/build.make:776: recipe for target 'src/external/cocotron/CoreGraphics/CoreGraphics' failed
make[2]: *** [src/external/cocotron/CoreGraphics/CoreGraphics] Error 1
CMakeFiles/Makefile2:53089: recipe for target 'src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics.dir/all' failed
make[1]: *** [src/external/cocotron/CoreGraphics/CMakeFiles/CoreGraphics.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu@10-8-28-125:~/darling/build$

**Comment by LubosD** [comment]
Should be fixed.

**Comment by cena-luo** [comment]
@LubosD   could you tell me how to fixed,please...  
btw, I want to user Mac shell,like codesign or any others, use this project will work nice?
