### ISSUE TITLE
Darling fails to build on Ubuntu 18.04 (clang 6.0.0)

### ISSUE THREAD

**Issue by ahyattdev** [darlinghq/darling#381]
```
[ 94%] Building CXX object src/external/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/runtime/JSGlobalObjectDebuggable.o
In file included from /home/andrewhyatt/darling/src/external/JavaScriptCore/runtime/JSGlobalObjectDebuggable.cpp:36:
In file included from /home/andrewhyatt/darling/src/external/JavaScriptCore/inspector/remote/RemoteInspector.h:35:
In file included from /home/andrewhyatt/darling/src/external/JavaScriptCore/inspector/remote/cocoa/RemoteInspectorXPCConnection.h:33:
/home/andrewhyatt/darling/src/external/WTF/include/wtf/spi/darwin/XPCSPI.h:98:6: error: conflicting types for 'xpc_array_apply'
bool xpc_array_apply(xpc_object_t, xpc_array_applier_t);
     ^
```

**Comment by panaC** [comment]
cat /etc/issue :
Ubuntu 18.04 LTS \n \l

I have an error on git clone recursive.
The submodule darlinghq/darling-WTF throw an error : 

> error: Server does not allow request for unadvertised object 49a9990781cdf767b06d5af988a34d13a688da99
Fetched in submodule path 'src/external/WTF', but it did not contain 49a9990781cdf767b06d5af988a34d13a688da99. Direct fetching of that commit failed.

Have you an idea ?

Thanks,

**Comment by stek29** [comment]
@panaC fixed in cafaf9752330

**Comment by panaC** [comment]
Thanks to you
