### ISSUE TITLE
Compiling issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by titus-leistner** [darlinghq/darling#71]
Hi,
I'm getting following error, when I try to compile on Ubuntu 14.04:

[ 76%] Building CXX object src/CoreFoundation/CMakeFiles/CoreFoundation.dir/CFPreferences.o
/home/xxxx/darling/src/CoreFoundation/CFPreferences.mm:26:10: error: cannot initialize return object of
      type 'CFPropertyListRef' (aka 'CFPropertyList _') with an rvalue of type 'id'
                return [[NSUserDefaults standardUserDefaults] objectForKey: (NSString_) key];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: **\* [src/CoreFoundation/CMakeFiles/CoreFoundation.dir/CFPreferences.o] Fehler 1
make[1]: **\* [src/CoreFoundation/CMakeFiles/CoreFoundation.dir/all] Fehler 2
make: **\* [all] Fehler 2
