### ISSUE TITLE
Errors while make lkm

### ISSUE THREAD

**Issue by goerster87** [darlinghq/darling#546]
When I run make lkm, I get the following output:

`dfoerster@app-dev:~/darling/darling/build$ make lkm
[  0%] Built target migcom
[  0%] Built target migexe
[100%] Built target lkm_generate
[100%] Building the Linux kernel module
make[4]: Entering directory '/home/dfoerster/darling/darling/src/lkm'
Running kernel version is 4.4.0-145-generic
rm -f darling-mach.mod.o
make -C /lib/modules/4.4.0-145-generic/build M=/home/dfoerster/darling/darling/src/lkm modules
make[5]: Entering directory '/usr/src/linux-headers-4.4.0-145-generic'
Running kernel version is 4.4.0-145-generic
Invoked by kernel build system, building for 4.4.0-145-generic
  CC [M]  /home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.o
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c: In function ‘foreignmm_init’:
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:27:11: error: implicit declaration of function ‘kthread_create_worker’ [-Werror=implicit-function-declaration]
  worker = kthread_create_worker(0, "darling-foreign_mm");
           ^
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:27:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  worker = kthread_create_worker(0, "darling-foreign_mm");
         ^
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c: In function ‘foreignmm_exit’:
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:32:2: error: implicit declaration of function ‘kthread_destroy_worker’ [-Werror=implicit-function-declaration]
  kthread_destroy_worker(worker);
  ^
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c: In function ‘foreignmm_execute’:
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:64:2: error: implicit declaration of function ‘kthread_init_work’ [-Werror=implicit-function-declaration]
  kthread_init_work(&work.kw, foreignmm_run);
  ^
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:65:2: error: implicit declaration of function ‘kthread_queue_work’ [-Werror=implicit-function-declaration]
  kthread_queue_work(worker, &work.kw);
  ^
/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.c:66:2: error: implicit declaration of function ‘kthread_flush_work’ [-Werror=implicit-function-declaration]
  kthread_flush_work(&work.kw);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:285: recipe for target '/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.o' failed
make[6]: *** [/home/dfoerster/darling/darling/src/lkm/darling/foreign_mm.o] Error 1
Makefile:1454: recipe for target '_module_/home/dfoerster/darling/darling/src/lkm' failed
make[5]: *** [_module_/home/dfoerster/darling/darling/src/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-4.4.0-145-generic'
Makefile:291: recipe for target 'default' failed
make[4]: *** [default] Error 2
make[4]: Leaving directory '/home/dfoerster/darling/darling/src/lkm'
src/lkm/CMakeFiles/lkm.dir/build.make:57: recipe for target 'src/lkm/CMakeFiles/lkm' failed
make[3]: *** [src/lkm/CMakeFiles/lkm] Error 2
CMakeFiles/Makefile2:45795: recipe for target 'src/lkm/CMakeFiles/lkm.dir/all' failed
make[2]: *** [src/lkm/CMakeFiles/lkm.dir/all] Error 2
CMakeFiles/Makefile2:45802: recipe for target 'src/lkm/CMakeFiles/lkm.dir/rule' failed
make[1]: *** [src/lkm/CMakeFiles/lkm.dir/rule] Error 2
Makefile:15946: recipe for target 'lkm' failed
make: *** [lkm] Error 2
`

Running on Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-145-generic x86_64)

**Comment by LubosD** [comment]
The kernel used in Ubuntu 16.04 is way too old.

**Comment by goerster87** [comment]
which kernel version do i need?

**Comment by ahyattdev** [comment]
It works in 18.04, not sure exactly which one is needed.

**Comment by ahyattdev** [comment]
Confirmed to work on `4.15.0-55-generic` (18.04). I guess we only support 18.04 and up now, unfortunately.
