### ISSUE TITLE
All answered problems on getting darling to build don't seem to work.

### ISSUE THREAD

**Issue by JoshuaAudreyMudanyi** [darlinghq/darling#1101]
**Build Log**
At the moment, I cannot build darling from source, I have tried multiple time to install darling-dkms to no avail, what the hell is going on, there is either no information on getting this to run on Distributor ID: Ubuntu, Description: Ubuntu 21.10, Release: 21.10, Codename: impish, or it really can't run on it
```
sudo gdebi darling-dkms_0.1.20210224.testing_amd64.deb

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done

Kernel module for Darling
Do you want to install the software package? [y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
Selecting previously unselected package darling-dkms.
(Reading database ... 276298 files and directories currently installed.)
Preparing to unpack darling-dkms_0.1.20210224.testing_amd64.deb ...
Unpacking darling-dkms (0.1.20210224~testing) ...
Setting up darling-dkms (0.1.20210224~testing) ...
>>> DKMS: Module add, build, and install

Creating symlink /var/lib/dkms/darling-mach/0.1/source ->
                 /usr/src/darling-mach-0.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
'make' -C lkm/ MIGDIR=/usr/src/darling-mach-0.1/miggen MIGDIR_REL=../miggen.........................(bad exit status: 2)
ERROR (dkms apport): unable to determine source package for darling-dkms
Error! Bad return status for module build on kernel: 5.13.0-28-generic (x86_64)
Consult /var/lib/dkms/darling-mach/0.1/build/make.log for more information.
dpkg: error processing package darling-dkms (--install):
 installed darling-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 darling-dkms
```
```
 make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.o] Error 1
 make[1]: *** [Makefile:1879: /var/lib/dkms/darling-mach/0.1/build/lkm] Error 2
 make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-28-generic'
 make: *** [Makefile:615: default] Error 2
 make: Leaving directory '/var/lib/dkms/darling-mach/0.1/build/lkm'
DKMSKernelVersion: 5.13.0-28-generic
Date: Sun Feb  6 12:13:17 2022
DuplicateSignature: dkms:darling-dkms:0.1.20210224~testing:/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c:208:75: error: ‘TIF_IA32’ undeclared (first use in this function)
Package: darling-dkms 0.1.20210224~testing
PackageVersion: 0.1.20210224~testing
SourcePackage: darling
Title: darling-dkms 0.1.20210224~testing: darling-mach kernel module failed to build
```
```
In file included from ./include/linux/fcntl.h:6,
                 from ./include/linux/fs.h:26,
                 from ./include/linux/huge_mm.h:8,
                 from ./include/linux/mm.h:726,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct.h:55,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c:36:
./include/uapi/linux/fcntl.h:99: note: this is the location of the previous definition
   99 | #define AT_EACCESS              0x200   /* Test access permitted for
      | 
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c: In function ‘thread_get_state_internal’:
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c:208:75: error: ‘TIF_IA32’ undeclared (first use in this function)
  208 |                         if (!test_ti_thread_flag(task_thread_info(ltask), TIF_IA32))
      |                                                                           ^~~~~~~~
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c:208:75: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c: In function ‘thread_set_state’:
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.c:495:83: error: ‘TIF_IA32’ undeclared (first use in this function)
  495 |                                 if (!test_ti_thread_flag(task_thread_info(ltask), TIF_IA32))
      |                                                                                   ^~~~~~~~
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct_kern_thread_act.o] Error 1
make[1]: *** [Makefile:1879: /var/lib/dkms/darling-mach/0.1/build/lkm] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-28-generic'
make: *** [Makefile:615: default] Error 2
make: Leaving directory '/var/lib/dkms/darling-mach/0.1/build/lkm'
```

**System Information**
uname -a

Linux HP-EliteBook-8440p 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

| Software | Version |
| --- | --- |
| Clang | 13.0.0-2 |
| CMake | 3.18.4 |
| Linux Kernel | 5.13.0-28-generic |
| Darling | ... |

**Comment by facekapow** [comment]
Closing this as we no longer use a kernel module.
