### ISSUE TITLE
Lego Digital Designer/_kCTFontAttributeName

### ISSUE THREAD

**Issue by s6fnrich** [darlinghq/darling#575]
dyld: Symbol not found: _kCTFontAttributeName
  Referenced from: /Applications/LEGO Digital Designer.app/Contents/MacOS/LEGO Digital Designer
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
 in /Applications/LEGO Digital Designer.app/Contents/MacOS/LEGO Digital Designer
Abort trap: 6 (core dumped)

**Comment by Lukeekul** [comment]
Same issue for me:
dyld: Symbol not found: _kCTFontAttributeName
  Referenced from: /Applications/Nord Sound Manager v7.52.app/Contents/MacOS/Nord Sound Manager
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
 in /Applications/Nord Sound Manager v7.52.app/Contents/MacOS/Nord Sound Manager
Abort trap: 6 (core dumped)

Build with clang 9.0.0 and the patch from Issue #573

**Comment by Arucard1983** [comment]
Also a Mac OS X port of my research program requires this symbol.
