### ISSUE TITLE
Cannot compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by liftchampion** [darlinghq/darling#532]
**Compilation error:** `...darling/src/external/foundation/src/NSCallBacks.m:253:11: error: use of undeclared identifier 'o' return [o isEqual: p];;`
Installed as it told in your site after update/upgrade.
Tried `cmake -DFULL_BUILD=OFF ..` - then I got a lot of ranlib errors `no symbols` (I don't have a screenshot unfortunately. It's at around 35%)
Tried `make -j4` - same result `undeclared identifier`
Tried re-call make in both ways - same result.
Screenshots of term with error and system info are below:
![Screenshot_2019-06-12_11-26-40](https://user-images.githubusercontent.com/42142932/59337657-b573d480-8d09-11e9-92a9-ee8aa184ba97.png)
![Screenshot_2019-06-12_11-42-34](https://user-images.githubusercontent.com/42142932/59337689-c02e6980-8d09-11e9-8755-8432fd851bf2.png)
Thank you

**Comment by bugaevc** [comment]
Yeah, that temporary. You'd have to either revert https://github.com/darlinghq/darling-foundation/commit/9b8d545ed53af4ff16a31d45280f028794ab170c or wait till we land https://github.com/darlinghq/darling-foundation/pull/5.

**Comment by liftchampion** [comment]
Nice, thank you @bugaevc

**Comment by kamillys** [comment]
@liftchampion can you bump darling-foundation?

**Comment by liftchampion** [comment]
@kamillys yes, I've checked out to the mentioned commit. Now there is now problem with this step.
But now I got **error** at around 60% without any description. Details in the image below.

Not very useful:
After it I called `make --debug`, but unfortunately I forgot the result.
Then I tried to call `make re`, your makefile hasn't such rule, but it did something and said that everything is ok. When I called `make` after it, I got same error as in ussue's top.

![Screenshot_2019-06-14_03-17-07](https://user-images.githubusercontent.com/42142932/59475724-c92c5180-8e55-11e9-8cbc-496a490b16b1.png)

**Comment by bugaevc** [comment]
> But now I got error at around 60% without any description.

That either means that there is a description somewhere above (this can happen if you're building with `-j` and other processes output their stuff after the error), or some process was OOM-killed by the kernel.

In both cases there next thing to do is to try building without `-j` and seeing whether that goes through or gives you an error message.

Anyway, the error must be that we haven't landed https://github.com/darlinghq/darling/pull/531, and actually let me do that...

**Comment by liftchampion** [comment]
@bugaevc yes, really error message could be lost. Sorry, I haven't seen your post, so I updated my previous comment (UPD3 and one picture in bottom with -d output).
Now I've ran it with `--output-sync`, hope it'll help.

**Comment by liftchampion** [comment]
@bugaevc I think I've found the error!
![Screenshot_2019-06-14_09-22-47](https://user-images.githubusercontent.com/42142932/59487749-3f48ac80-8e86-11e9-98eb-db6a00c10181.png)

**Comment by bugaevc** [comment]
Yeah, I've told you that already :D

> Anyway, the error must be that we haven't landed #531, and actually let me do that...

Now that it's merged, you just need to pull

**Comment by kamillys** [comment]
src/external/foundation still needs to be updated to master to compile.

**Comment by kamillys** [comment]
https://github.com/darlinghq/darling/pull/533 update src/external/foundation to master (64c8cc)

**Comment by liftchampion** [comment]
@kamillys @bugaevc **Compiled!** Thanks for your help.
Note that foundation submodule not in 64c8cc-commit in project's master-branch. Without this commit not working
Thank you

**Comment by yslan** [comment]
> Note that foundation submodule not in 64c8cc-commit in project's master-branch. Without this commit not working

I encountered the same issue on Ubuntu 18.04
As liftchampion said, darling's HEAD doesn't use the latest working foundation submodule. 
After replace that, I can compile.

Thank you.

**Comment by flylzj** [comment]
@yslan I got the same error on Arch. Could you tell me how to fix it. Thank you.

**Comment by yslan** [comment]
I simply remove the foundation under src/external/, and git clone the latest version of foundation https://github.com/darlinghq/darling-foundation to replace that. Then, it works for me.

**Comment by flylzj** [comment]
@yslan thank you for your replay. I  run `cd ../src/external/foundation && git pull`.It successly compiled too.By the way, 两岸人民一家亲 :smile:
